name: base
channels:
  - jzuhone
  - sherpa
  - anaconda
  - glueviz
  - astropy
  - phlya
  - http://ssb.stsci.edu/astroconda
  - defaults
  - conda-forge
dependencies:
    - plotly=4.9.0=py_0    
    - pandas=1.1.0=py37hb1e8313_0
    - streamlit==0.69.2
    - numpy=1.19.1=py37h3b9f5b6_0
    - numpy-base=1.19.1=py37hcfb5961_0
    - numpydoc=1.1.0=py_0
  
